############################
#       MinePoS v1.0.1     #
#    Thank you For Using   #
#         MinePoS          #
############################


API:
   # If you are running MinePoS Lite please enter your link given to you in your admin panel
   Link: "http://serverid.minepos.me/index.php&r=api/api"
   Key: "APIKEYHERE"

messages:
   prefix: "&7[&cMinePoS&7]&r "
   error: "&7Sorry there was a error please contact a member of staff"
   noperm: "&7Sorry you do not have access to run this command"
   success: "&7Thank you &c%player%&7, Your donation has been processed and you should have received your items"
   open: "&7Opened the store"
   linkwait: "&7Please wait while we generate your link"
   link: "&7Your Link is: &c%link%"
   # Set this to true to enable debug output in console
   debug: false

settings:
   # How often should the plugin look for new orders to be processed (in mins)
   # Default: 2
   # Recommended: 2
   pollingrate: 2
   command: "buy"